// Forge extension TypeScript declarations
// Generated by forge-app/src/bin/generate_forge_types.rs
// Do not edit manually.

type JsonValue = any;

export type ForgeProjectSettings = { omni_enabled: boolean, omni_config: OmniConfig | null, };

export type ProjectConfig = { project_id: string, custom_executors: JsonValue | null, forge_config: JsonValue | null, };

export type OmniConfig = { enabled: boolean, host: string | null, api_key: string | null, instance: string | null, recipient: string | null, recipient_type: RecipientType | null, };

export type RecipientType = "PhoneNumber" | "UserId";

export type OmniInstance = { instance_name: string, channel_type: string, display_name: string, status: string, is_healthy: boolean, };

export type SendTextRequest = { phone_number: string | null, user_id: string | null, text: string, };

export type SendTextResponse = { success: boolean, message_id: string | null, status: string, error: string | null, };
